package com.redhat.colpensiones;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-08-13T14:52:03.669-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "AfiliadoWSService", 
                  wsdlLocation = "file:/D:/assert/proyectos/RH-Colpensiones/colpensiones-find/wsdl/AfiliadoWS.wsdl",
                  targetNamespace = "http://colpensiones.redhat.com/") 
public class AfiliadoWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://colpensiones.redhat.com/", "AfiliadoWSService");
    public final static QName AfiliadoWSPort = new QName("http://colpensiones.redhat.com/", "AfiliadoWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/assert/proyectos/RH-Colpensiones/colpensiones-find/wsdl/AfiliadoWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AfiliadoWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/assert/proyectos/RH-Colpensiones/colpensiones-find/wsdl/AfiliadoWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AfiliadoWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AfiliadoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AfiliadoWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AfiliadoWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AfiliadoWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AfiliadoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AfiliadoWSI
     */
    @WebEndpoint(name = "AfiliadoWSPort")
    public AfiliadoWSI getAfiliadoWSPort() {
        return super.getPort(AfiliadoWSPort, AfiliadoWSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AfiliadoWSI
     */
    @WebEndpoint(name = "AfiliadoWSPort")
    public AfiliadoWSI getAfiliadoWSPort(WebServiceFeature... features) {
        return super.getPort(AfiliadoWSPort, AfiliadoWSI.class, features);
    }

}
