package com.redhat.colpensiones;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-08-13T14:52:03.612-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://colpensiones.redhat.com/", name = "AfiliadoWSI")
@XmlSeeAlso({ObjectFactory.class})
public interface AfiliadoWSI {

    @WebResult(name = "return", targetNamespace = "http://colpensiones.redhat.com/", partName = "return")
    @WebMethod
    public Afiliado buscarAfiliado(
        @WebParam(partName = "numeroDocumento", name = "numeroDocumento")
        java.lang.String numeroDocumento,
        @WebParam(partName = "tipoDocumento", name = "tipoDocumento")
        java.lang.String tipoDocumento
    );
}
