package co.gov.colpensiones.contracts._1_0.personas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-08-03T17:10:17.363-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "SvcDocumento", 
                  wsdlLocation = "file:/home/aromero/git/POC-Colpensiones/colpensiones/wsdl/SvcDocumento.wsdl",
                  targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas") 
public class SvcDocumento extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.colpensiones.gov.co/contracts/1.0/personas", "SvcDocumento");
    public final static QName EndpointDocumento = new QName("http://www.colpensiones.gov.co/contracts/1.0/personas", "EndpointDocumento");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/aromero/git/POC-Colpensiones/colpensiones/wsdl/SvcDocumento.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SvcDocumento.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/aromero/git/POC-Colpensiones/colpensiones/wsdl/SvcDocumento.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SvcDocumento(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SvcDocumento(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SvcDocumento() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SvcDocumento(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SvcDocumento(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SvcDocumento(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ContratoSvcDocumento
     */
    @WebEndpoint(name = "EndpointDocumento")
    public ContratoSvcDocumento getEndpointDocumento() {
        return super.getPort(EndpointDocumento, ContratoSvcDocumento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContratoSvcDocumento
     */
    @WebEndpoint(name = "EndpointDocumento")
    public ContratoSvcDocumento getEndpointDocumento(WebServiceFeature... features) {
        return super.getPort(EndpointDocumento, ContratoSvcDocumento.class, features);
    }

}
