package co.gov.colpensiones.contracts._1_0.personas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-08-03T17:08:49.037-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", name = "ContratoRegistroArchivosNuevo")
@XmlSeeAlso({ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, co.gov.colpensiones.schemas._1_0.comun.errores.ObjectFactory.class, co.gov.colpensiones.schemas._1_0.comun.tramites.ObjectFactory.class, co.gov.colpensiones.schemas._1_0.comun.ObjectFactory.class, co.gov.colpensiones.schemas._1_0.personas.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContratoRegistroArchivosNuevo {

    @WebResult(name = "DocumentosTRDDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "DocumentosTRDDTO")
    @WebMethod(operationName = "RegistrarArchivosNuevo", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoRegistroArchivosNuevo/RegistrarArchivosNuevo")
    public co.gov.colpensiones.schemas._1_0.personas.TipoDocumentosTRDDTO registrarArchivosNuevo(
        @WebParam(partName = "InformacionRegistroNuevo", name = "InformacionRegistroNuevo", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas._1_0.personas.TipoInformacionRegistroNuevo informacionRegistroNuevo
    );
}
