package co.gov.colpensiones.contracts._1_0.personas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-07-28T19:14:49.011-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", name = "ContratoSvcDocumento")
@XmlSeeAlso({ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, co.gov.colpensiones.schemas._1_0.comun.errores.ObjectFactory.class, co.gov.colpensiones.schemas._1_0.comun.tramites.ObjectFactory.class, co.gov.colpensiones.schemas._1_0.comun.ObjectFactory.class, co.gov.colpensiones.schemas._1_0.personas.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContratoSvcDocumento {

    @WebResult(name = "DocumentoDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "DocumentoDTO")
    @WebMethod(operationName = "ObtenerDocumento", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcDocumento/ObtenerDocumento")
    public co.gov.colpensiones.schemas._1_0.personas.TipoDocumentoDTO obtenerDocumento(
        @WebParam(partName = "IdentificacionDocumentoDTO", name = "IdentificacionDocumentoDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas._1_0.personas.TipoIdentificacionDocumentoDTO identificacionDocumentoDTO
    );

    @WebResult(name = "DocumentosTRDDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "DocumentosTRDDTO")
    @WebMethod(operationName = "RegistrarArchivosTRD", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcDocumento/RegistrarArchivosTRD")
    public co.gov.colpensiones.schemas._1_0.personas.TipoDocumentosTRDDTO registrarArchivosTRD(
        @WebParam(partName = "InformacionRegistroTRDDTO", name = "InformacionRegistroTRDDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas._1_0.personas.TipoInformacionRegistroTRDDTO informacionRegistroTRDDTO
    );

    @WebResult(name = "DigitalizadosDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "DigitalizadosDTO")
    @WebMethod(operationName = "ConsultarDigitalizados", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcDocumento/ConsultarDigitalizados")
    public co.gov.colpensiones.schemas._1_0.personas.TipoDigitalizadosDTO consultarDigitalizados(
        @WebParam(partName = "CriteriosConsultaDigitalizadosDTO", name = "CriteriosConsultaDigitalizadosDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas._1_0.personas.TipoInformacionConsultaDigitalizadosDTO criteriosConsultaDigitalizadosDTO
    );

    @WebResult(name = "ObtenerDocumentoTRD", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "ObtenerDocumentoTRD")
    @WebMethod(operationName = "ObtenerDocumentoTRD", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcDocumento/ObtenerDocumentoTRD")
    public co.gov.colpensiones.schemas._1_0.personas.TipoObtenerDocumentosTRD obtenerDocumentoTRD(
        @WebParam(partName = "IdentificacionDocumentoTRD", name = "IdentificacionDocumentoTRD", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas._1_0.personas.TipoIdentificacionDocumentoTRD identificacionDocumentoTRD
    );

    @WebResult(name = "DocumentoDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "DocumentoDTO")
    @WebMethod(operationName = "ActualizarMetadata", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcDocumento/ActualizarMetadata")
    public co.gov.colpensiones.schemas._1_0.personas.TipoDocumentoDTO actualizarMetadata(
        @WebParam(partName = "InformacionActualizarDTO", name = "InformacionActualizarDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas._1_0.personas.TipoInformacionActualizarMetadataDTO informacionActualizarDTO
    );

    @WebResult(name = "DocumentosTRD", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "DocumentosTRD")
    @WebMethod(operationName = "ConsultarDocumentosTRD", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcDocumento/ConsultarDocumentosTRD")
    public co.gov.colpensiones.schemas._1_0.personas.TipoDocumentoConsultaTRD consultarDocumentosTRD(
        @WebParam(partName = "CriteriosConsultaTRD", name = "CriteriosConsultaTRD", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas._1_0.personas.TipoInformacionConsultaDocumentosTRD criteriosConsultaTRD
    );

    @WebResult(name = "EstadoEjecucion", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "EstadoEjecucion")
    @WebMethod(operationName = "MoverDocumentoTRD", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcDocumento/MoverDocumentoTRD")
    public co.gov.colpensiones.schemas._1_0.comun.errores.TipoEstadoEjecucion moverDocumentoTRD(
        @WebParam(partName = "InformacionMovimientoDocumentoTRDDTO", name = "InformacionMovimientoDocumentoTRDDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas._1_0.personas.TipoInformacionMovimientoDocumentoTRDDTO informacionMovimientoDocumentoTRDDTO
    );
}
